import Parse from "parse";

const PARSE_APPLICATION_ID = process.env.REACT_APP_BACK4APP_APPLICATION_ID;
const PARSE_JAVASCRIPT_KEY = process.env.REACT_APP_BACK4APP_JAVASCRIPT_KEY;
const PARSE_HOST_URL = process.env.REACT_APP_BACK4APP_SERVER_URL;

Parse.initialize(PARSE_APPLICATION_ID, PARSE_JAVASCRIPT_KEY);
Parse.serverURL = PARSE_HOST_URL;

export default Parse;
